# Generated by Django 4.2.7 on 2023-11-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0005_alter_fotografia_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galaxia"),
                    ("PLANETA", "Planeta"),
                    ("CORPO CELESTE", "Corpo Celeste"),
                ],
                default="-",
                max_length=100,
            ),
        ),
    ]
